version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "JoeyRudd"
    assignees:
      - "JoeyRudd"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "JoeyRudd"
    assignees:
      - "JoeyRudd"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions (exclude problematic Railway action)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "JoeyRudd"
    assignees:
      - "JoeyRudd"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Exclude Railway action from Dependabot updates to prevent 404/403 errors
      - dependency-name: "railway/deploy"
