version: 2
updates:
  # Python dependencies - ONLY security updates and minor versions
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"  # Changed from weekly to monthly
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2  # Reduced from 5
    reviewers:
      - "JoeyRudd"
    assignees:
      - "JoeyRudd"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Only allow patch and minor updates, no major versions
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates that could break things
    ignore:
      - dependency-name: "fastapi"  # Core framework - update manually
      - dependency-name: "pydantic"  # Core framework - update manually
      - dependency-name: "uvicorn"   # Core framework - update manually
      - dependency-name: "scikit-learn"  # ML library - update manually
      - dependency-name: "sentence-transformers"  # ML library - update manually

  # Node.js dependencies - ONLY security updates and minor versions
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"  # Changed from weekly to monthly
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2  # Reduced from 5
    reviewers:
      - "JoeyRudd"
    assignees:
      - "JoeyRudd"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Only allow patch and minor updates, no major versions
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates that could break things
    ignore:
      - dependency-name: "vue"  # Core framework - update manually
      - dependency-name: "vite"  # Build tool - update manually
      - dependency-name: "tailwindcss"  # CSS framework - update manually
      - dependency-name: "typescript"  # Language - update manually
      - dependency-name: "@vitejs/plugin-vue"  # Plugin - update manually

  # GitHub Actions - ONLY security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"  # Keep monthly
    open-pull-requests-limit: 1  # Reduced from 3
    reviewers:
      - "JoeyRudd"
    assignees:
      - "JoeyRudd"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Only allow security updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Exclude Railway action from Dependabot updates to prevent 404/403 errors
      - dependency-name: "railway/deploy"
      # Exclude actions that could change deployment behavior
      - dependency-name: "actions/checkout"
      - dependency-name: "actions/setup-python"
      - dependency-name: "actions/setup-node"
